language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script: yarn test
branches:
  only:
    - "/.*/"
before_deploy: yarn build
after_success:
  - chmod ugo+x ./deploy.py
  - ./deploy.py
