language: node_js
node_js:
  - "10"
cache:
  directories:
    - node_modules
script: yarn test
branches:
  only:
    - "/.*/"
after_success:
  - yarn build
  - chmod ugo+x ./deploy.sh
  - ./deploy.sh
